name: Android Release Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive # Ensure all submodules are checked out recursively

    - name: Update submodules recursively
      run: git submodule update --init --recursive

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        ndk: '25.1.8937393'  # Specify the NDK version you need

    - name: Create local.properties
      working-directory: moonlight-android
      run: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
        echo "ndk.dir=$ANDROID_NDK_ROOT" >> local.properties

    - name: Prepare Gradle Wrapper
      working-directory: moonlight-android
      run: ./gradlew wrapper

    - name: Build Release APK
      working-directory: moonlight-android
      run: ./gradlew assembleRelease

    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: moonlight-android/app/build/outputs/apk/release/*.apk
